/**
 * AI matchday recommendations (PRD §11 Phase 3 — AI recommendations).
 *
 * Wraps the Phase 1 RecommendationService and adds a natural-language matchday
 * pitch generated by Claude. Key-optional: when ANTHROPIC_API_KEY is set it
 * calls the Anthropic API; otherwise it falls back to a deterministic "smart"
 * summary so the endpoint always works offline and in CI.
 */
import Anthropic from "@anthropic-ai/sdk";
import type { ApiEnv } from "../config/env.js";
import { teamName } from "../config/teamNames.js";
import type { Recommendation, RecommendationService } from "./recommendations.js";
import { log } from "../util/logger.js";

export interface AiRecommendation extends Recommendation {
  /** Natural-language matchday pitch. */
  aiSummary: string;
  /** True if generated by Claude, false if the heuristic fallback was used. */
  aiGenerated: boolean;
}

export interface AiRecommendQuery {
  city: string;
  origin: { lat: number; lon: number };
  radiusMeters: number;
  team: string;
  limit?: number;
}

export class AiRecommendationService {
  private readonly client: Anthropic | null;

  constructor(
    private readonly recommendations: RecommendationService,
    private readonly env: ApiEnv,
  ) {
    this.client = env.anthropicApiKey
      ? new Anthropic({ apiKey: env.anthropicApiKey })
      : null;
  }

  async recommend(q: AiRecommendQuery): Promise<AiRecommendation> {
    const base = await this.recommendations.recommend({
      city: q.city,
      origin: q.origin,
      radiusMeters: q.radiusMeters,
      team: q.team,
      limit: q.limit ?? 5,
    });

    const aiResult = this.client
      ? await this.generateWithClaude(base)
      : null;

    return {
      ...base,
      aiSummary: aiResult ?? this.heuristicSummary(base),
      aiGenerated: aiResult !== null,
    };
  }

  private buildContext(rec: Recommendation): string {
    const venues = rec.topVenues
      .slice(0, 5)
      .map(
        (v, i) =>
          `${i + 1}. ${v.name} (${v.kind}, ${Math.round(v.distanceMeters)}m away, match score ${Math.round(
            v.finalScore * 100,
          )}/100${v.supportsTeams.length ? `, supports ${v.supportsTeams.join("/")}` : ""})`,
      )
      .join("\n");
    const matches = rec.upcomingMatches
      .slice(0, 3)
      .map((m) => `- ${m.homeTeam} vs ${m.awayTeam} (${m.kickoff}${m.stage ? `, ${m.stage}` : ""})`)
      .join("\n");
    return [
      `Fan supports: ${teamName(rec.team)} (${rec.team})`,
      `City: ${rec.city}`,
      `Top nearby venues:\n${venues || "(none found)"}`,
      `Upcoming fixtures:\n${matches || "(none)"}`,
    ].join("\n\n");
  }

  private async generateWithClaude(rec: Recommendation): Promise<string | null> {
    if (!this.client) return null;
    try {
      const message = await this.client.messages.create({
        model: this.env.aiModel,
        max_tokens: 400,
        system:
          "You are FanMatch's matchday concierge. Given a soccer fan's team, city, nearby venues, and upcoming fixtures, write a warm, specific 2-3 sentence recommendation for where to watch. Name 1-2 actual venues from the list and tie them to an upcoming fixture when relevant. Be concise and energetic; no preamble, no lists, no markdown.",
        messages: [
          { role: "user", content: this.buildContext(rec) },
        ],
      });
      const text = message.content
        .filter((b): b is Anthropic.TextBlock => b.type === "text")
        .map((b) => b.text)
        .join("")
        .trim();
      return text || null;
    } catch (err) {
      log.warn("ai: Claude call failed, using heuristic fallback", {
        error: err instanceof Error ? err.message : String(err),
      });
      return null;
    }
  }

  /** Deterministic fallback summary built from the same data. */
  private heuristicSummary(rec: Recommendation): string {
    const team = teamName(rec.team);
    const top = rec.topVenues[0];
    const next = rec.upcomingMatches[0];
    if (!top) {
      return `No standout ${team} spots turned up nearby yet — widen your search radius to find more watch venues.`;
    }
    const second = rec.topVenues[1];
    const venuePart =
      second && top
        ? `${top.name} (${Math.round(top.distanceMeters)}m) is your best bet, with ${second.name} close behind`
        : `${top.name} is your best bet, ${Math.round(top.distanceMeters)}m away`;
    const matchPart = next
      ? ` Catch ${next.homeTeam} vs ${next.awayTeam} there with fellow ${team} fans.`
      : ` A solid spot to watch with fellow ${team} fans.`;
    return `${venuePart}.${matchPart}`;
  }
}
